{"statusCode":500,"status":"error","level":"error","message":"Error This is a test error","stack":"Error: This is a test error\n    at exports.login (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\controllers\\authController.js:46:9)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\middleware\\validateRequest.js:20:5\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"statusCode":500,"status":"error","level":"error","message":"Error This is a test error","stack":"Error: This is a test error\n    at exports.login (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\controllers\\authController.js:46:9)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\middleware\\validateRequest.js:20:5\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"statusCode":500,"status":"error","level":"error","message":"Error This is a test error","stack":"Error: This is a test error\n    at exports.login (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\controllers\\authController.js:46:9)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\middleware\\validateRequest.js:20:5\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"statusCode":500,"status":"error","level":"error","message":"Error This is a test error","stack":"Error: This is a test error\n    at exports.login (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\controllers\\authController.js:46:9)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\middleware\\validateRequest.js:20:5\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"statusCode":500,"status":"error","level":"error","message":"Error This is a test error","stack":"Error: This is a test error\n    at exports.login (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\controllers\\authController.js:46:9)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\middleware\\validateRequest.js:20:5\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"statusCode":500,"status":"error","level":"error","message":"Error This is a test error","stack":"Error: This is a test error\n    at exports.login (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\controllers\\authController.js:46:9)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\middleware\\validateRequest.js:20:5\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"statusCode":500,"status":"error","level":"error","message":"This is a test error This is a test error","stack":"Error: This is a test error\n    at exports.login (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\controllers\\authController.js:46:9)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\middleware\\validateRequest.js:20:5\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:137:13)\n    at Route.dispatch (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\route.js:112:3)\n    at newFn (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express-async-errors\\index.js:16:20)\n    at Layer.handle [as handle_request] (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:281:22\n    at Function.process_params (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:335:12)\n    at next (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at Function.handle (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:174:3)\n    at router (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\express\\lib\\router\\index.js:47:12)"}
{"level":"error","message":"This is an uncaughtException This is an uncaughtException","stack":"Error: This is an uncaughtException\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js:21:7)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"code":"MODULE_NOT_FOUND","requireStack":["C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js","C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js"],"level":"error","message":"Cannot find module './router/authRoutes'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js Cannot find module './router/authRoutes'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js","stack":"Error: Cannot find module './router/authRoutes'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:842:27)\n    at Module.require (internal/modules/cjs/loader.js:1026:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js:2:20)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n    at Module.require (internal/modules/cjs/loader.js:1026:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js:37:1)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)"}
{"code":"MODULE_NOT_FOUND","requireStack":["C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js","C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js"],"level":"error","message":"Cannot find module './router/authRoutes'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js Cannot find module './router/authRoutes'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js","stack":"Error: Cannot find module './router/authRoutes'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:842:27)\n    at Module.require (internal/modules/cjs/loader.js:1026:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js:2:20)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n    at Module.require (internal/modules/cjs/loader.js:1026:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js:29:1)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)"}
{"code":"MODULE_NOT_FOUND","requireStack":["C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js","C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js"],"level":"error","message":"Cannot find module './utils/appError'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js Cannot find module './utils/appError'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js","stack":"Error: Cannot find module './utils/appError'\nRequire stack:\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js\n- C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js\n    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)\n    at Function.Module._load (internal/modules/cjs/loader.js:842:27)\n    at Module.require (internal/modules/cjs/loader.js:1026:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js:9:18)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n    at Module.require (internal/modules/cjs/loader.js:1026:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js:29:1)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)"}
{"level":"error","message":"app is not defined app is not defined","stack":"ReferenceError: app is not defined\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\routes.js:21:1)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n    at Module.require (internal/modules/cjs/loader.js:1026:19)\n    at require (internal/modules/cjs/helpers.js:72:18)\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js:29:1)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"message":"Successfully connected to MongoDB","level":"info"}
{"message":"Successfully connected to MongoDB","level":"info"}
{"message":"bad auth Authentication failed. bad auth Authentication failed.","reason":{"type":"ReplicaSetNoPrimary","setName":null,"maxSetVersion":null,"maxElectionId":null,"servers":{},"stale":false,"compatible":true,"compatibilityError":null,"logicalSessionTimeoutMinutes":null,"heartbeatFrequencyMS":10000,"localThresholdMS":15,"commonWireVersion":null},"level":"error","stack":"MongooseServerSelectionError: bad auth Authentication failed.\n    at NativeConnection.Connection.openUri (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\mongoose\\lib\\connection.js:827:32)\n    at Mongoose.connect (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\node_modules\\mongoose\\lib\\index.js:335:15)\n    at module.exports (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\startup\\db.js:6:6)\n    at Object.<anonymous> (C:\\WorkingDir\\Development\\Nodejs\\Front-Backend-Api-Auth\\server\\server.js:27:24)\n    at Module._compile (internal/modules/cjs/loader.js:1138:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)\n    at Module.load (internal/modules/cjs/loader.js:986:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:879:14)\n    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)\n    at internal/main/run_main_module.js:17:47"}
{"message":"Successfully connected to MongoDB","level":"info"}
{"message":"Successfully connected to MongoDB","level":"info"}
{"message":"Successfully connected to MongoDB","level":"info"}
{"message":"Successfully connected to MongoDB","level":"info"}
{"message":"Successfully connected to MongoDB","level":"info"}
{"message":"Successfully connected to MongoDB","level":"info"}
